<a href="https://colab.research.google.com/github/SentineNet-AI-SpringBoard/SentinelNet-AI/blob/SENTINELNET-AI-KUSHAGRA/MILESTONE2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.impute import SimpleImputer
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import StandardScaler

In [2]:
df = pd.read_csv('/content/drive/MyDrive/collab sentinl net ai/Wednesday-workingHours.pcap_ISCX.csv')

In [3]:
df.head()

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,80,38308,1,1,6,6,6,6,6.000000,0.000000,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
1,389,479,11,5,172,326,79,0,15.636364,31.449238,...,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
2,88,1095,10,6,3150,3150,1575,0,315.000000,632.561635,...,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
3,389,15206,17,12,3452,6660,1313,0,203.058823,425.778474,...,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
4,88,1092,9,6,3150,3152,1575,0,350.000000,694.509719,...,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN


In [31]:
df.describe()

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,Bwd Packet Length Max,Bwd Packet Length Min,Bwd Packet Length Mean,Bwd Packet Length Std,Flow Bytes/s,Flow Packets/s,Flow IAT Mean,Flow IAT Std,Flow IAT Max,Flow IAT Min,Fwd IAT Total,Fwd IAT Mean,Fwd IAT Std,Fwd IAT Max,Fwd IAT Min,Bwd IAT Total,Bwd IAT Mean,Bwd IAT Std,Bwd IAT Max,Bwd IAT Min,Fwd PSH Flags,Bwd PSH Flags,Fwd URG Flags,Bwd URG Flags,Fwd Header Length,Bwd Header Length,Fwd Packets/s,Bwd Packets/s,Min Packet Length,Max Packet Length,Packet Length Mean,Packet Length Std,Packet Length Variance,FIN Flag Count,SYN Flag Count,RST Flag Count,PSH Flag Count,ACK Flag Count,URG Flag Count,CWE Flag Count,ECE Flag Count,Down/Up Ratio,Average Packet Size,Avg Fwd Segment Size,Avg Bwd Segment Size,Fwd Header Length.1,Fwd Avg Bytes/Bulk,Fwd Avg Packets/Bulk,Fwd Avg Bulk Rate,Bwd Avg Bytes/Bulk,Bwd Avg Packets/Bulk,Bwd Avg Bulk Rate,Subflow Fwd Packets,Subflow Fwd Bytes,Subflow Bwd Packets,Subflow Bwd Bytes,Init_Win_bytes_forward,Init_Win_bytes_backward,act_data_pkt_fwd,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min
count,692703.000000,6.927030e+05,692703.000000,692703.000000,6.927030e+05,6.927030e+05,692703.000000,692703.000000,692703.000000,692703.000000,692703.000000,692703.000000,692703.000000,692703.000000,6.916950e+05,6.927030e+05,6.927030e+05,6.927030e+05,6.927030e+05,6.927030e+05,6.927030e+05,6.927030e+05,6.927030e+05,6.927030e+05,6.927030e+05,6.927030e+05,6.927030e+05,6.927030e+05,6.927030e+05,6.927030e+05,692703.000000,692703.0,692703.0,692703.0,6.927030e+05,6.927030e+05,6.927030e+05,6.927030e+05,692703.000000,692703.000000,692703.000000,692703.000000,6.927030e+05,692703.000000,692703.000000,692703.000000,692703.000000,692703.000000,692703.000000,692703.0,692703.000000,692703.000000,692703.000000,692703.000000,692703.000000,6.927030e+05,692703.0,692703.0,692703.0,692703.0,692703.0,692703.0,692703.000000,6.927030e+05,692703.000000,6.927030e+05,692703.000000,692703.000000,692703.000000,692703.000000,6.927030e+05,6.927030e+05,6.927030e+05,6.927030e+05,6.927030e+05,6.927030e+05,6.927030e+05,6.927030e+05
mean,5686.869462,2.800168e+07,9.556261,10.214079,5.550930e+02,1.699644e+04,233.593936,15.022183,60.555440,82.895863,1661.546313,33.832924,551.940841,658.636320,inf,inf,2.502809e+06,6.844318e+06,2.289307e+07,2.224592e+05,2.774476e+07,5.069287e+06,9.016685e+06,2.279837e+07,1.030778e+06,1.386407e+07,2.647068e+06,3.522882e+06,9.305284e+06,9.268549e+05,0.042201,0.0,0.0,0.0,2.420580e+02,2.492460e+02,9.545305e+04,4.052544e+03,13.723771,1725.129073,278.246605,523.265612,8.876018e+05,0.097301,0.042201,0.000338,0.193693,0.418049,0.066372,0.0,0.000339,0.556957,305.664882,60.555440,551.940841,2.420580e+02,0.0,0.0,0.0,0.0,0.0,0.0,9.556261,5.550930e+02,10.214079,1.699489e+04,5299.671256,1476.643078,6.121279,26.761141,9.224478e+04,4.760852e+04,1.627363e+05,6.315186e+04,2.211122e+07,4.743744e+05,2.252174e+07,2.173373e+07
std,15727.423560,4.276680e+07,747.197814,984.204633,6.163663e+03,2.241175e+06,603.751856,51.068835,157.643794,226.126084,2613.924428,64.586498,797.449564,1098.043102,NaN,NaN,5.595945e+06,1.175401e+07,3.839395e+07,3.673248e+06,4.277094e+07,1.103613e+07,1.600574e+07,3.843629e+07,8.866760e+06,3.335293e+07,9.593760e+06,1.073828e+07,2.616633e+07,8.107914e+06,0.201048,0.0,0.0,0.0,1.564277e+04,1.968957e+04,3.198607e+05,3.091927e+04,27.521716,2634.372188,369.130494,783.442461,1.748895e+06,0.296368,0.201048,0.018376,0.395192,0.493239,0.248931,0.0,0.018416,0.570734,398.045939,157.643794,797.449564,1.564277e+04,0.0,0.0,0.0,0.0,0.0,0.0,747.197814,6.163663e+03,984.204633,2.240953e+06,11869.737394,7315.272621,715.155068,6.322368,7.007049e+05,4.742081e+05,1.094616e+06,6.051023e+05,3.812415e+07,4.488512e+06,3.848292e+07,3.807725e+07
min,0.000000,-1.000000e+00,1.000000,

In [ ]:
DF['Label']

In [32]:
df[' Label'] = df[' Label'].astype(str)

In [33]:
x = df.iloc[:,0:78]
y = df[' Label']

In [34]:
df_encoded = pd.get_dummies(df, columns=[' Label'], drop_first=True)
display(df_encoded.head())

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,Bwd Packet Length Max,Bwd Packet Length Min,Bwd Packet Length Mean,Bwd Packet Length Std,Flow Bytes/s,Flow Packets/s,Flow IAT Mean,Flow IAT Std,Flow IAT Max,Flow IAT Min,Fwd IAT Total,Fwd IAT Mean,Fwd IAT Std,Fwd IAT Max,Fwd IAT Min,Bwd IAT Total,Bwd IAT Mean,Bwd IAT Std,Bwd IAT Max,Bwd IAT Min,Fwd PSH Flags,Bwd PSH Flags,Fwd URG Flags,Bwd URG Flags,Fwd Header Length,Bwd Header Length,Fwd Packets/s,Bwd Packets/s,Min Packet Length,Max Packet Length,...,FIN Flag Count,SYN Flag Count,RST Flag Count,PSH Flag Count,ACK Flag Count,URG Flag Count,CWE Flag Count,ECE Flag Count,Down/Up Ratio,Average Packet Size,Avg Fwd Segment Size,Avg Bwd Segment Size,Fwd Header Length.1,Fwd Avg Bytes/Bulk,Fwd Avg Packets/Bulk,Fwd Avg Bulk Rate,Bwd Avg Bytes/Bulk,Bwd Avg Packets/Bulk,Bwd Avg Bulk Rate,Subflow Fwd Packets,Subflow Fwd Bytes,Subflow Bwd Packets,Subflow Bwd Bytes,Init_Win_bytes_forward,Init_Win_bytes_backward,act_data_pkt_fwd,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label_DoS GoldenEye,Label_DoS Hulk,Label_DoS Slowhttptest,Label_DoS slowloris,Label_Heartbleed
0,80,38308,1,1,6,6,6,6,6.000000,0.000000,6,6,6.000000,0.000000,3.132505e+02,52.208416,38308.000000,0.000000,38308,38308,0,0.000000,0.000000,0,0,0,0.000000,0.000000,0,0,0,0,0,0,20,20,26.104208,26.104208,6,6,...,0,0,0,0,1,1,0,0,1,9.000000,6.000000,6.000000,20,0,0,0,0,0,0,1,6,1,6,255,946,0,20,0.0,0.0,0,0,0.0,0.0,0,0,False,False,False,False,False
1,389,479,11,5,172,326,79,0,15.636364,31.449238,163,0,65.200000,89.278777,1.039666e+06,33402.922760,31.933333,25.510409,73,0,479,47.900000,38.942836,109,1,401,100.250000,101.736178,237,3,0,0,0,0,368,176,22964.509390,10438.413360,0,163,...,0,0,0,1,0,0,0,0,0,31.125000,15.636364,65.200000,368,0,0,0,0,0,0,11,172,5,326,29200,260,4,32,0.0,0.0,0,0,0.0,0.0,0,0,False,False,False,False,False
2,88,1095,10,6,3150,3150,1575,0,315.000000,632.561635,1575,0,525.000000,813.326503,5.753425e+06,14611.872150,73.000000,204.960972,810,1,1095,121.666667,298.746130,915,1,995,199.000000,345.535092,810,3,0,0,0,0,336,208,9132.420091,5479.452055,0,1575,...,0,0,0,1,0,0,0,0,0,393.750000,315.000000,525.000000,336,0,0,0,0,0,0,10,3150,6,3150,29200,2081,3,32,0.0,0.0,0,0,0.0,0.0,0,0,False,False,False,False,False
3,389,15206,17,12,3452,6660,1313,0,203.058823,425.778474,3069,0,555.000000,977.480342,6.650007e+05,1907.141918,543.071429,2519.931377,13391,0,15206,950.375000,3322.417812,13391,2,15112,1373.818182,4176.449588,13961,3,0,0,0,0,560,388,1117.979745,789.162173,0,3069,...,0,0,0,1,0,0,0,0,0,348.689655,203.058823,555.000000,560,0,0,0,0,0,0,17,3452,12,6660,29200,0,10,32,0.0,0.0,0,0,0.0,0.0,0,0,False,False,False,False,False
4,88,1092,9,6,3150,3152,1575,0,350.000000,694.509719,1576,0,525.333333,813.842901,5.771062e+06,13736.263740,78.000000,207.000929,794,1,1092,136.500000,313.850738,910,1,1015,203.000000,333.240154,794,3,0,0,0,0,304,208,8241.758242,5494.505495,0,1576,...,0,0,0,1,0,0,0,0,0,420.133333,350.000000,525.333333,304,0,0,0,0,0,0,9,3150,6,3152,29200,2081,2,32,0.0,0.0,0,0,0.0,0.0,0,0,False,False,False,False,False


In [35]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state=42)

In [36]:
x_train.shape

(554162, 78)

In [37]:
# Replace infinities with NaN
x_train = x_train.replace([np.inf, -np.inf], np.nan)
x_test = x_test.replace([np.inf, -np.inf], np.nan)

In [38]:
# Impute missing values
imputer = SimpleImputer(strategy='mean')
x_train_imputed = imputer.fit_transform(x_train)
x_test_imputed = imputer.transform(x_test)

In [41]:
#Scale features
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train_imputed)
x_test_scaled = scaler.transform(x_test_imputed)

In [42]:
# Apply PCA (retain 95% variance)
pca = PCA(n_components=0.95, random_state=42)
x_train_pca = pca.fit_transform(x_train_scaled)
x_test_pca = pca.transform(x_test_scaled)

# Logistic Regression with efficient solver and parallelization  

In [43]:
#Logistic Regression with efficient solver and parallelization
model = LogisticRegression(max_iter=200, solver='saga', n_jobs=-1)
model.fit(x_train_pca, y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


LogisticRegression(max_iter=200, n_jobs=-1, solver='saga')

In [44]:
#Predictions and evaluation
y_pred = model.predict(x_test_pca)

In [46]:
print("=== Logistic Regression (Optimized) ===")
print("Accuracy:", round(accuracy_score(y_test, y_pred), 4))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

=== Logistic Regression (Optimized) ===
Accuracy: 0.9628
Confusion Matrix:
 [[85520   123  2332   129    66     0]
 [  175  1723    97    21     1     0]
 [ 1271    50 44816     5     5     0]
 [  266     0    10   796    18     0]
 [  551     0     1    23   539     0]
 [    0     0     3     0     0     0]]


/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


Classification Report:
                   precision    recall  f1-score   support

          BENIGN       0.97      0.97      0.97     88170
   DoS GoldenEye       0.91      0.85      0.88      2017
        DoS Hulk       0.95      0.97      0.96     46147
DoS Slowhttptest       0.82      0.73      0.77      1090
   DoS slowloris       0.86      0.48      0.62      1114
      Heartbleed       0.00      0.00      0.00         3

        accuracy                           0.96    138541
       macro avg       0.75      0.67      0.70    138541
    weighted avg       0.96      0.96      0.96    138541



/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


# Support vector machine

In [47]:
from sklearn.svm import SVC


Let's train and evaluate the Support Vector Machine model using `sklearn.svm.SVC`.

In [ ]:
from sklearn.svm import SVC

# Initialize and train the SVC model
# Note: Training an SVC model on a large dataset can take a significant amount of time.
# You might consider using a subset of the data or a linear kernel for faster training.
svm_model = SVC(kernel='linear') # Using a linear kernel for faster training as an example
svm_model.fit(x_train_pca, y_train)

# Make predictions on the test set
y_pred_svm = svm_model.predict(x_test_pca)

# Evaluate the model
accuracy_svm = accuracy_score(y_test, y_pred_svm)
report_svm = classification_report(y_test, y_pred_svm)
matrix_svm = confusion_matrix(y_test, y_pred_svm)

print("SVM Model Evaluation:")
print(f"Accuracy: {accuracy_svm}")
print("Classification Report:")
print(report_svm)
print("Confusion Matrix:")
print(matrix_svm)

In [ ]:
!pip install -q cudf-cu12 cuml-cu12 --extra-index-url=https://pypi.nvidia.com


In [ ]:
from cuml.svm import SVC

In [ ]:
from sklearn.preprocessing import StandardScaler, LabelEncoder
from cuml.svm import SVC
import cupy as cp

# Scale the imputed data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(x_train_imputed)
X_test_scaled = scaler.transform(x_test_imputed)

# Encode the labels
label_encoder = LabelEncoder()
y_train_encoded = label_encoder.fit_transform(y_train)
y_test_encoded = label_encoder.transform(y_test)

# Convert data to CuPy arrays for cuml
X_train_gpu = cp.asarray(X_train_scaled)
X_test_gpu = cp.asarray(X_test_scaled)
y_train_gpu = cp.asarray(y_train_encoded)


# Train SVM on GPU
model = SVC(kernel='rbf', C=1.0, gamma='scale')
model.fit(X_train_gpu, y_train_gpu)

SVC()

In [ ]:
y_pred = model.predict(X_test_gpu)
accuracy = accuracy_score(y_test_encoded, y_pred.get())
accuracy

0.9902122837282826

In [ ]:
print(classification_report(y_test_encoded, y_pred.get(), target_names=label_encoder.classes_))

                  precision    recall  f1-score   support

          BENIGN       1.00      0.99      0.99     88170
   DoS GoldenEye       0.99      0.96      0.97      2017
        DoS Hulk       0.98      1.00      0.99     46147
DoS Slowhttptest       0.97      0.98      0.97      1090
   DoS slowloris       0.98      0.94      0.96      1114
      Heartbleed       1.00      1.00      1.00         3

        accuracy                           0.99    138541
       macro avg       0.99      0.98      0.98    138541
    weighted avg       0.99      0.99      0.99    138541



In [ ]:
cm = confusion_matrix(y_test_encoded, y_pred.get())
cm_df = pd.DataFrame(cm, index=label_encoder.classes_, columns=label_encoder.classes_)
cm_df

,BENIGN,DoS GoldenEye,DoS Hulk,DoS Slowhttptest,DoS slowloris,Heartbleed
BENIGN,87044,14,1082,20,10,0
DoS GoldenEye,69,1932,16,0,0,0
DoS Hulk,60,0,46087,0,0,0
DoS Slowhttptest,11,0,0,1071,8,0
DoS slowloris,47,1,1,17,1048,0
Heartbleed,0,0,0,0,0,3


# Random forest classifier


In [ ]:
from cuml.ensemble import RandomForestClassifier

In [ ]:
import cudf
df = cudf.read_csv("/content/drive/MyDrive/collab sentinl net ai/Wednesday-workingHours.pcap_ISCX.csv")
df.columns = df.columns.str.strip()

In [ ]:
X = df.drop(columns=['Label'])
y = df['Label'].astype(str)

In [ ]:
encoder = LabelEncoder()
y = encoder.fit_transform(y.to_numpy())

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)


In [ ]:
from cuml.preprocessing import StandardScaler
import numpy as np # Import numpy for np.inf and np.nan

# Replace infinite values with NaN in cuDF DataFrames
X_train = X_train.replace([np.inf, -np.inf], np.nan)
X_test = X_test.replace([np.inf, -np.inf], np.nan)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
rf_gpu = RandomForestClassifier(
    n_estimators=200,
    max_depth=16,
    n_streams=8,        # GPU parallel threads
    random_state=42
)
rf_gpu.fit(X_train, y_train)

RandomForestClassifier()

In [ ]:
y_pred = rf_gpu.predict(X_test)




In [ ]:
accuracy = accuracy_score(y_test, y_pred.to_numpy())
accuracy

0.9976035974909955

In [ ]:
cm = confusion_matrix(y_test, y_pred.to_numpy())
cm_df = pd.DataFrame(cm, index=encoder.classes_, columns=encoder.classes_)
cm_df

,BENIGN,DoS GoldenEye,DoS Hulk,DoS Slowhttptest,DoS slowloris,Heartbleed
BENIGN,87740,3,250,13,0,0
DoS GoldenEye,12,2041,6,0,0,0
DoS Hulk,38,0,46177,0,0,0
DoS Slowhttptest,5,1,0,1093,1,0
DoS slowloris,2,0,0,1,1156,0
Heartbleed,0,0,0,0,0,2


In [ ]:
print(classification_report(y_test, y_pred.to_numpy(), target_names=encoder.classes_))

                  precision    recall  f1-score   support

          BENIGN       1.00      1.00      1.00     88006
   DoS GoldenEye       1.00      0.99      0.99      2059
        DoS Hulk       0.99      1.00      1.00     46215
DoS Slowhttptest       0.99      0.99      0.99      1100
   DoS slowloris       1.00      1.00      1.00      1159
      Heartbleed       1.00      1.00      1.00         2

        accuracy                           1.00    138541
       macro avg       1.00      1.00      1.00    138541
    weighted avg       1.00      1.00      1.00    138541

